apiVersion: v2
name: netbird-combined
description: NetBird combined server - management, signal, relay, STUN, dashboard, and optional proxy in a combined deployment
type: application
version: 0.3.0
appVersion: "0.70.4"

dependencies:
  - name: netbird-dashboard-lib
    version: 0.1.0
    repository: file://../netbird-dashboard-lib
  - name: netbird-proxy-lib
    version: 0.1.0
    repository: file://../netbird-proxy-lib
