apiVersion: v2
name: netbird
description: A Helm chart for NetBird
type: application
version: 0.1.1
appVersion: "0.50.1"
dependencies:
- name: dashboard
  version: "0.1.1"
  condition: dashboard.enabled
- name: management
  version: "0.1.1"
  condition: management.enabled
- name: signal
  version: "0.1.1"
  condition: signal.enabled
- name: relay
  version: "0.1.1"
  condition: relay.enabled
