---
global:
  zulip:
    postgresql:
      appSecretName: my-pg-secret
    rabbitmq:
      defaultUserSecretName: my-rabbitmq-secret
    redis:
      secretName: my-redis-secret
zulip:
  settings:
    administratorEmail: admin@example.com
    externalHost: zulip.example.com
  secrets:
    secretKey: test-secret-key
cnpg:
  auth:
    existingSecret: my-pg-secret
rabbitmq:
  defaultUserSecret: my-rabbitmq-secret
redis:
  auth:
    existingSecret: my-redis-secret
web:
  connections:
    redis:
      passwordFromSecret: true
tornado:
  connections:
    redis:
      passwordFromSecret: true
worker:
  connections:
    redis:
      passwordFromSecret: true
singleton:
  connections:
    redis:
      passwordFromSecret: true
