---
zulip:
  settings:
    administratorEmail: admin@example.com
    externalHost: zulip.example.com
  secrets:
    secretKey: test-secret-key
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::role/zulip
  name: custom-zulip-sa
memcached:
  memcachedPassword: test-memcached
rabbitmq:
  auth:
    password: test-rabbitmq
    erlangCookie: test-cookie
redis:
  auth:
    password: test-redis
cnpg:
  auth:
    password: test-pg-zulip
