{{/*
Expand the name of the chart.
*/}}
{{- define "zulip.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "zulip.fullname" -}}
{{- $globalZulip := (.Values.global).zulip | default dict -}}
{{- if $globalZulip.name }}
{{- $globalZulip.name | trunc 63 | trimSuffix "-" }}
{{- else if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "zulip.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "zulip.labels" -}}
helm.sh/chart: {{ include "zulip.chart" . }}
{{ include "zulip.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "zulip.selectorLabels" -}}
app.kubernetes.io/name: {{ include "zulip.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "zulip.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "zulip.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}


{{/*
Name of the CloudNativePG Cluster managed by this chart.
*/}}
{{- define "zulip.cnpg.name" -}}
{{- default (printf "%s-postgresql" (include "zulip.fullname" .)) .Values.cnpg.name | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Secret containing the CNPG application user's credentials.
*/}}
{{- define "zulip.cnpg.appSecretName" -}}
{{- if .Values.cnpg.auth.existingSecret -}}
{{- .Values.cnpg.auth.existingSecret -}}
{{- else -}}
{{- printf "%s-app" (include "zulip.cnpg.name" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end }}

{{/*
Name of the RabbitmqCluster managed by this chart.
*/}}
{{- define "zulip.rabbitmq.name" -}}
{{- default (printf "%s-rabbitmq" (include "zulip.fullname" .)) .Values.rabbitmq.name | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Secret generated by the RabbitMQ Cluster Operator for the default user.
*/}}
{{- define "zulip.rabbitmq.defaultUserSecret" -}}
{{- default (printf "%s-default-user" (include "zulip.rabbitmq.name" .)) .Values.rabbitmq.defaultUserSecret | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Name of the in-chart Memcached service.
*/}}
{{- define "zulip.memcached.name" -}}
{{- printf "%s-memcached" (include "zulip.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Name of the in-chart Redis service.
*/}}
{{- define "zulip.redis.name" -}}
{{- printf "%s-redis" (include "zulip.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Secret containing the in-chart Redis password.
*/}}
{{- define "zulip.redis.secretName" -}}
{{- if .Values.redis.auth.existingSecret -}}
{{- .Values.redis.auth.existingSecret -}}
{{- else -}}
{{- printf "%s-auth" (include "zulip.redis.name" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end }}

{{/*
Stable release-wide Zulip remote cache prefix.

Upstream Zulip stores this in var/remote_cache_prefix on a shared deployment
directory. In Kubernetes each pod has its own filesystem, so we render the
same deterministic 32-hex-character prefix plus trailing colon everywhere.
*/}}
{{- define "zulip.remoteCachePrefix" -}}
{{- $cache := .Values.zulip.cache | default dict -}}
{{- $seed := get $cache "remoteCachePrefixSeed" | default "" -}}
{{- if not $seed -}}
{{- $seed = printf "%s/%s/%s" .Release.Namespace .Release.Name "remote-cache" -}}
{{- end -}}
{{- printf "%s:" (sha256sum $seed | trunc 32) -}}
{{- end }}

{{/*
Name of the ConfigMap containing non-secret native environment variables.
*/}}
{{- define "zulip.envConfigMapName" -}}
{{- printf "%s-env" (include "zulip.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end }}

{{/*
Name of the Secret containing chart-managed scalar Zulip secret variables.
*/}}
{{- define "zulip.envSecretName" -}}
{{- printf "%s-env" (include "zulip.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end }}

{{/*
Shared envFrom sources for every Zulip container.
*/}}
{{- define "zulip.envFrom" -}}
- configMapRef:
    name: {{ include "zulip.envConfigMapName" . }}
- secretRef:
    name: {{ include "zulip.envSecretName" . }}
    optional: true
{{- end }}

{{/*
Non-secret scalar native environment entries rendered into the shared ConfigMap.
*/}}
{{- define "zulip.envConfigData" -}}
{{- $globalZulip := (.Values.global).zulip | default dict -}}
{{- $globalExtraEnv := get $globalZulip "extraEnv" | default dict -}}
{{- $extraEnv := mergeOverwrite (deepCopy $globalExtraEnv) (.Values.zulip.extraEnv | default dict) -}}
{{- $objectStorage := .Values.zulip.objectStorage | default dict -}}
{{- if and (get $objectStorage "enabled") (get $objectStorage "caBundle") (not (hasKey $extraEnv "AWS_CA_BUNDLE")) }}
AWS_CA_BUNDLE: "/etc/zulip/s3-ca.crt"
{{- end }}
{{- if and (get $objectStorage "enabled") (get $objectStorage "caBundle") (not (hasKey $extraEnv "SSL_CERT_FILE")) }}
SSL_CERT_FILE: "/etc/zulip/s3-ca.crt"
{{- end }}
{{- range $key, $value := $extraEnv }}
{{- if not (kindIs "map" $value) }}
{{ $key }}: {{ $value | toString | quote }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Scalar secret entries rendered into the shared Secret. These become
/etc/zulip/zulip-secrets.conf via the runtime prepare script.
*/}}
{{- define "zulip.envSecretData" -}}
{{- $globalZulip := (.Values.global).zulip | default dict -}}
{{- $globalExtraEnv := get $globalZulip "extraEnv" | default dict -}}
{{- $nativeSecrets := .Values.zulip.secrets | default dict }}
{{- if not (hasKey $globalExtraEnv "ZULIP_SECRET_secret_key") }}
ZULIP_SECRET_secret_key: {{ get $nativeSecrets "secretKey" | default "change-me-zulip-secret-key" | quote }}
{{- end }}
{{- if not (hasKey $globalExtraEnv "ZULIP_SECRET_shared_secret") }}
ZULIP_SECRET_shared_secret: {{ get $nativeSecrets "sharedSecret" | default "change-me-zulip-shared-secret" | quote }}
{{- end }}
{{- if not (hasKey $globalExtraEnv "ZULIP_SECRET_avatar_salt") }}
ZULIP_SECRET_avatar_salt: {{ get $nativeSecrets "avatarSalt" | default "change-me-zulip-avatar-salt" | quote }}
{{- end }}
{{- if and (not (hasKey $globalExtraEnv "ZULIP_SECRET_postgres_password")) (not .Values.cnpg.enabled) (not (kindIs "map" .Values.externalPostgresql.password)) .Values.externalPostgresql.password }}
ZULIP_SECRET_postgres_password: {{ .Values.externalPostgresql.password | quote }}
{{- end }}
{{- if and (not (hasKey $globalExtraEnv "ZULIP_SECRET_rabbitmq_password")) (not .Values.rabbitmq.enabled) (not (kindIs "map" .Values.externalRabbitmq.password)) .Values.externalRabbitmq.password }}
ZULIP_SECRET_rabbitmq_password: {{ .Values.externalRabbitmq.password | quote }}
{{- end }}
{{- if .Values.memcached.enabled }}
{{- if and (not (hasKey $globalExtraEnv "ZULIP_SECRET_memcached_password")) .Values.memcached.memcachedPassword }}
ZULIP_SECRET_memcached_password: {{ .Values.memcached.memcachedPassword | quote }}
{{- end }}
{{- else if and (not (hasKey $globalExtraEnv "ZULIP_SECRET_memcached_password")) (not (kindIs "map" .Values.externalMemcached.password)) .Values.externalMemcached.password }}
ZULIP_SECRET_memcached_password: {{ .Values.externalMemcached.password | quote }}
{{- end }}
{{- if and (not (hasKey $globalExtraEnv "ZULIP_SECRET_redis_password")) .Values.redis.enabled .Values.redis.auth.password (not .Values.redis.auth.existingSecret) }}
ZULIP_SECRET_redis_password: {{ .Values.redis.auth.password | quote }}
{{- else if and (not (hasKey $globalExtraEnv "ZULIP_SECRET_redis_password")) (not .Values.redis.enabled) (not (kindIs "map" .Values.externalRedis.password)) .Values.externalRedis.password }}
ZULIP_SECRET_redis_password: {{ .Values.externalRedis.password | quote }}
{{- end }}
{{- $objectStorage := .Values.zulip.objectStorage | default dict }}
{{- if and (get $objectStorage "enabled") (get $objectStorage "accessKey") (not (hasKey $globalExtraEnv "ZULIP_SECRET_s3_key")) }}
ZULIP_SECRET_s3_key: {{ get $objectStorage "accessKey" | quote }}
{{- end }}
{{- if and (get $objectStorage "enabled") (get $objectStorage "secretKey") (not (hasKey $globalExtraEnv "ZULIP_SECRET_s3_secret_key")) }}
ZULIP_SECRET_s3_secret_key: {{ get $objectStorage "secretKey" | quote }}
{{- end }}
{{- end }}

{{/*
Inline native env entries that must remain valueFrom references.
*/}}
{{- define "zulip.env" -}}
{{- if .Values.cnpg.enabled }}
- name: ZULIP_SECRET_postgres_password
  valueFrom:
    secretKeyRef:
      name: {{ include "zulip.cnpg.appSecretName" . }}
      key: {{ .Values.cnpg.auth.passwordKey | default "password" }}
{{- else if kindIs "map" .Values.externalPostgresql.password }}
- name: ZULIP_SECRET_postgres_password
  {{- toYaml .Values.externalPostgresql.password | nindent 2 }}
{{- end }}
{{- if .Values.rabbitmq.enabled }}
- name: ZULIP_SETTING_RABBITMQ_USERNAME
  valueFrom:
    secretKeyRef:
      name: {{ include "zulip.rabbitmq.defaultUserSecret" . }}
      key: username
- name: ZULIP_SECRET_rabbitmq_password
  valueFrom:
    secretKeyRef:
      name: {{ include "zulip.rabbitmq.defaultUserSecret" . }}
      key: password
{{- else if kindIs "map" .Values.externalRabbitmq.password }}
- name: ZULIP_SECRET_rabbitmq_password
  {{- toYaml .Values.externalRabbitmq.password | nindent 2 }}
{{- end }}
{{- if and .Values.redis.enabled .Values.redis.auth.existingSecret }}
- name: ZULIP_SECRET_redis_password
  valueFrom:
    secretKeyRef:
      name: {{ include "zulip.redis.secretName" . }}
      key: {{ .Values.redis.auth.existingSecretPasswordKey | default "redis-password" }}
{{- else if and (not .Values.redis.enabled) (kindIs "map" .Values.externalRedis.password) }}
- name: ZULIP_SECRET_redis_password
  {{- toYaml .Values.externalRedis.password | nindent 2 }}
{{- end }}
{{- if and (not .Values.memcached.enabled) (kindIs "map" .Values.externalMemcached.password) }}
- name: ZULIP_SECRET_memcached_password
  {{- toYaml .Values.externalMemcached.password | nindent 2 }}
{{- end }}
{{- $globalZulip := (.Values.global).zulip | default dict }}
{{- $extraEnv := get $globalZulip "extraEnv" | default dict }}
{{- range $key, $value := $extraEnv }}
{{- if kindIs "map" $value }}
- name: {{ $key }}
  {{- toYaml $value | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}

{{/* Kubernetes-native runtime/config names. */}}
{{- define "zulip.runtimeConfigMapName" -}}
{{- $globalZulip := (.Values.global).zulip | default dict -}}
{{- default (printf "%s-runtime" (include "zulip.fullname" .)) (get $globalZulip "runtimeConfigMapName" | default "") | trunc 63 | trimSuffix "-" -}}
{{- end }}

{{- define "zulip.appConfigMapName" -}}
{{- $globalZulip := (.Values.global).zulip | default dict -}}
{{- default (printf "%s-app-config" (include "zulip.fullname" .)) (get $globalZulip "appConfigMapName" | default "") | trunc 63 | trimSuffix "-" -}}
{{- end }}

{{- define "zulip.djangoServiceName" -}}
{{- printf "%s-django" (include "zulip.fullname" .) | trunc 63 | trimSuffix "-" -}}
{{- end }}

{{- define "zulip.tornadoServicePrefix" -}}
{{- printf "%s-tornado" (include "zulip.fullname" .) | trunc 57 | trimSuffix "-" -}}
{{- end }}

{{- define "zulip.k8sVolumeMounts" -}}
- name: zulip-runtime
  mountPath: /opt/zulip-k8s
  readOnly: true
- name: zulip-config-template
  mountPath: /etc/zulip-template
  readOnly: true
- name: zulip-etc
  mountPath: /etc/zulip
{{- end }}

{{- define "zulip.k8sVolumes" -}}
- name: zulip-runtime
  configMap:
    name: {{ include "zulip.runtimeConfigMapName" . }}
    defaultMode: 0755
- name: zulip-config-template
  configMap:
    name: {{ include "zulip.appConfigMapName" . }}
    defaultMode: 0444
- name: zulip-etc
  emptyDir: {}
{{- end }}

{{- define "zulip.tornadoPorts" -}}
{{- join " " (toStrings .Values.tornado.ports) -}}
{{- end }}

{{- define "zulip.settingsPy" -}}
{{- $settings := .Values.zulip.settings | default dict -}}
{{- $objectStorage := .Values.zulip.objectStorage | default dict -}}
{{- $s3SkipProxy := true -}}
{{- if hasKey $objectStorage "skipProxy" -}}
{{- $s3SkipProxy = get $objectStorage "skipProxy" -}}
{{- end -}}
{{- $externalHost := get $settings "externalHost" | default "zulip.example.com" -}}
{{- $admin := get $settings "administratorEmail" | default "admin@example.com" -}}
{{- $scheme := default "https://" (get $settings "externalUriScheme") -}}
{{- $authBackends := get $settings "authenticationBackends" | default (list "zproject.backends.EmailAuthBackend") -}}
from typing import Any

ZULIP_ADMINISTRATOR = {{ $admin | quote }}
EXTERNAL_HOST = {{ $externalHost | quote }}
EXTERNAL_URI_SCHEME = {{ $scheme | quote }}
AUTHENTICATION_BACKENDS = (
{{- range $backend := $authBackends }}
    {{ $backend | quote }},
{{- end }}
)

{{- if .Values.cnpg.enabled }}
REMOTE_POSTGRES_HOST = {{ printf "%s-rw" (include "zulip.cnpg.name" .) | quote }}
REMOTE_POSTGRES_PORT = "5432"
REMOTE_POSTGRES_SSLMODE = {{ .Values.cnpg.sslmode | default "prefer" | quote }}
{{- else }}
REMOTE_POSTGRES_HOST = {{ required "externalPostgresql.host is required when cnpg.enabled is false" .Values.externalPostgresql.host | quote }}
REMOTE_POSTGRES_PORT = {{ .Values.externalPostgresql.port | toString | quote }}
REMOTE_POSTGRES_SSLMODE = {{ .Values.externalPostgresql.sslmode | default "prefer" | quote }}
{{- end }}
{{- if .Values.rabbitmq.enabled }}
RABBITMQ_HOST = {{ include "zulip.rabbitmq.name" . | quote }}
RABBITMQ_PORT = 5672
RABBITMQ_USERNAME = ""
{{- else }}
RABBITMQ_HOST = {{ required "externalRabbitmq.host is required when rabbitmq.enabled is false" .Values.externalRabbitmq.host | quote }}
RABBITMQ_PORT = {{ .Values.externalRabbitmq.port }}
RABBITMQ_USERNAME = {{ .Values.externalRabbitmq.user | default "zulip" | quote }}
{{- end }}
{{- if .Values.memcached.enabled }}
MEMCACHED_LOCATION = {{ printf "%s:%v" (include "zulip.memcached.name" .) .Values.memcached.service.port | quote }}
MEMCACHED_USERNAME = {{ ternary .Values.memcached.memcachedUsername "" (and (not (empty .Values.memcached.memcachedUsername)) (not (empty .Values.memcached.memcachedPassword))) | quote }} or None
{{- else }}
MEMCACHED_LOCATION = {{ printf "%s:%v" (required "externalMemcached.host is required when memcached.enabled is false" .Values.externalMemcached.host) .Values.externalMemcached.port | quote }}
MEMCACHED_USERNAME = {{ .Values.externalMemcached.user | default "" | quote }} or None
{{- end }}
{{- if .Values.redis.enabled }}
REDIS_HOST = {{ include "zulip.redis.name" . | quote }}
REDIS_PORT = {{ .Values.redis.service.port }}
{{- else }}
REDIS_HOST = {{ required "externalRedis.host is required when redis.enabled is false" .Values.externalRedis.host | quote }}
REDIS_PORT = {{ .Values.externalRedis.port }}
{{- end }}

TORNADO_PORTS = [{{ join ", " (toStrings .Values.tornado.ports) }}]
USING_PGROONGA = {{ ternary "True" "False" (and .Values.cnpg.pgroonga.enabled .Values.cnpg.pgroonga.configureZulip) }}
KATEX_SERVER = {{ ternary "True" "False" (and .Values.web.katex.enabled true) }}
KATEX_SERVER_PORT = {{ .Values.web.katex.port | default 9700 }}
CAMO_URI = {{ ternary "/external_content/" "" (and .Values.web.camo.enabled true) | quote }}
LOCAL_UPLOADS_DIR = None

{{- if get $objectStorage "enabled" }}
S3_AUTH_UPLOADS_BUCKET = {{ get $objectStorage "uploadsBucket" | quote }}
S3_AVATAR_BUCKET = {{ get $objectStorage "avatarBucket" | quote }}
{{- if get $objectStorage "endpointUrl" }}
S3_ENDPOINT_URL = {{ get $objectStorage "endpointUrl" | quote }}
{{- end }}
{{- if get $objectStorage "avatarPublicUrlPrefix" }}
S3_AVATAR_PUBLIC_URL_PREFIX = {{ get $objectStorage "avatarPublicUrlPrefix" | quote }}
{{- end }}
{{- if get $objectStorage "region" }}
S3_REGION = {{ get $objectStorage "region" | quote }}
{{- end }}
S3_ADDRESSING_STYLE = {{ get $objectStorage "addressingStyle" | default "auto" | quote }}
S3_SKIP_PROXY = {{ ternary "True" "False" $s3SkipProxy }}
S3_UPLOADS_STORAGE_CLASS = {{ get $objectStorage "uploadsStorageClass" | default "STANDARD" | quote }}
S3_SKIP_CHECKSUM = {{ ternary "True" "False" (get $objectStorage "skipChecksum" | default false) }}
{{- end }}

{{- with get $settings "extraPython" }}
{{ . }}
{{- end }}
{{- end }}

{{- define "zulip.zulipConf" -}}
{{- $queueMultiprocess := .Values.zulip.queueWorkers.multiprocess | default false -}}
[machine]
deploy_type = production

[postgresql]
database_user = {{ ternary .Values.cnpg.auth.username (.Values.externalPostgresql.user | default "zulip") .Values.cnpg.enabled }}
database_name = {{ ternary .Values.cnpg.auth.database (.Values.externalPostgresql.database | default "zulip") .Values.cnpg.enabled }}

[application_server]
http_only = true
queue_workers_multiprocess = {{ ternary "true" "false" $queueMultiprocess }}
uwsgi_processes = {{ .Values.web.django.uwsgiProcesses | default 2 }}
uwsgi_listen_backlog_limit = {{ .Values.web.django.uwsgiListenBacklog | default 128 }}
mobile_notification_shards = {{ .Values.worker.shards.mobileNotifications | default 1 }}
user_activity_shards = {{ .Values.worker.shards.userActivity | default 1 }}
katex_server = {{ ternary "true" "false" .Values.web.katex.enabled }}
katex_server_port = {{ .Values.web.katex.port | default 9700 }}
tusd_server_listen = 0.0.0.0

{{- $rules := .Values.zulip.tornadoSharding.rules | default dict }}
{{- if or .Values.zulip.tornadoSharding.enabled (gt (len .Values.tornado.ports) 1) }}
[tornado_sharding]
{{- if $rules }}
{{- range $key, $value := $rules }}
{{ $key }} = {{ $value }}
{{- end }}
{{- else }}
{{ first .Values.tornado.ports }} = {{ .Values.zulip.settings.externalHost | default "zulip.example.com" }}
{{- end }}
{{- end }}
{{- with .Values.zulip.systemConfigExtra }}
{{ . }}
{{- end }}
{{- end }}

{{- define "zulip.shardingJson" -}}
{{- $rules := .Values.zulip.tornadoSharding.rules | default dict -}}
{{- if and .Values.zulip.tornadoSharding.enabled $rules -}}
{{- $settings := .Values.zulip.settings | default dict -}}
{{- $externalHost := get $settings "externalHost" | default "zulip.example.com" -}}
{{- $shardMap := dict -}}
{{- $regexes := list -}}
{{- range $key, $value := $rules -}}
{{- $rawKey := trimSuffix "_regex" $key -}}
{{- $portStrings := splitList "_" $rawKey -}}
{{- $ports := list -}}
{{- range $p := $portStrings }}{{- $ports = append $ports (int $p) -}}{{- end -}}
{{- $portValue := ternary (first $ports) $ports (eq (len $ports) 1) -}}
{{- if hasSuffix "_regex" $key -}}
{{- $regexes = append $regexes (list $value $portValue) -}}
{{- else -}}
{{- range $hostPart := splitList " " $value -}}
{{- if $hostPart -}}
{{- $host := ternary $hostPart (printf "%s.%s" $hostPart $externalHost) (contains "." $hostPart) -}}
{{- $_ := set $shardMap $host $portValue -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{ dict "shard_map" $shardMap "shard_regexes" $regexes | toJson }}
{{- else -}}
{}
{{- end -}}
{{- end }}

{{- define "zulip.uwsgiIni" -}}
[uwsgi]
strict=true
env=LANG=C.UTF-8
uid=zulip
gid=zulip
chdir=/home/zulip/deployments/current
module=zproject.wsgi:application
master=true
lazy-apps=true
http-socket=:{{ .Values.web.django.port | default 8080 }}
listen={{ .Values.web.django.uwsgiListenBacklog | default 128 }}
enable-threads=true
processes={{ .Values.web.django.uwsgiProcesses | default 2 }}
auto-procname=true
procname-prefix-spaced=zulip-django
harakiri={{ .Values.web.django.harakiri | default 55 }}
buffer-size=65535
post-buffering=4096
ignore-sigpipe=true
ignore-write-errors=true
disable-write-exception=true
vacuum=true
die-on-term=true
{{- end }}

{{- define "zulip.nginxConf" -}}
{{- $objectStorage := .Values.zulip.objectStorage | default dict -}}
{{- $s3Endpoint := get $objectStorage "endpointUrl" | default "" -}}
{{- $s3EndpointParts := dict -}}
{{- if $s3Endpoint -}}
{{- $s3EndpointParts = urlParse $s3Endpoint -}}
{{- end -}}
{{- $s3EndpointScheme := get $s3EndpointParts "scheme" | default "https" -}}
{{- $s3EndpointHost := get $s3EndpointParts "host" | default "" -}}
{{- $s3InternalHost := (splitList ":" $s3EndpointHost | first) -}}
{{- $avatarProxy := get $objectStorage "avatarProxy" | default dict -}}
{{- $avatarProxyEnabled := and (get $objectStorage "enabled") (get $avatarProxy "enabled") (get $avatarProxy "upstreamUrl") -}}
user zulip;
worker_processes auto;
error_log /dev/stderr info;
pid /tmp/nginx.pid;

events {
    worker_connections 4096;
}

http {
    access_log /dev/stdout combined;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    proxy_http_version 1.1;

    upstream django {
        server {{ include "zulip.djangoServiceName" . }}:{{ .Values.web.django.service.port | default .Values.web.django.port | default 8080 }};
        keepalive 128;
    }

{{- if .Values.web.tusd.enabled }}
    upstream tusd {
        server {{ include "zulip.djangoServiceName" . }}:{{ .Values.web.tusd.service.port | default .Values.web.tusd.port | default 9900 }};
        keepalive 64;
    }
{{- end }}

{{- range $port := .Values.tornado.ports }}
    upstream tornado{{ $port }} {
        server {{ include "zulip.tornadoServicePrefix" $ }}-{{ $port }}:{{ $port }};
        keepalive 1000;
    }
{{- end }}
{{- $rules := .Values.zulip.tornadoSharding.rules | default dict }}
{{- range $key, $_ := $rules }}
{{- $rawKey := trimSuffix "_regex" $key }}
{{- $portStrings := splitList "_" $rawKey }}
{{- if gt (len $portStrings) 1 }}
    upstream tornado{{ $rawKey }} {
        random;
{{- range $p := $portStrings }}
        server {{ include "zulip.tornadoServicePrefix" $ }}-{{ $p }}:{{ $p }};
{{- end }}
        keepalive 1000;
    }
{{- end }}
{{- end }}

    map $host $tornado_server {
        default http://tornado{{ first .Values.tornado.ports }};
{{- if and .Values.zulip.tornadoSharding.enabled $rules }}
{{- range $key, $value := $rules }}
{{- $rawKey := trimSuffix "_regex" $key }}
{{- if hasSuffix "_regex" $key }}
        ~*{{ $value }} http://tornado{{ $rawKey }};
{{- else }}
{{- range $hostPart := splitList " " $value }}
{{- if $hostPart }}
        {{ $hostPart }} http://tornado{{ $rawKey }};
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
    }

    map $http_x_forwarded_proto $zulip_forwarded_proto {
        default $http_x_forwarded_proto;
        "" $scheme;
    }

    server {
        listen {{ .Values.web.gateway.containerPort | default 80 }};
        server_name _;
        client_max_body_size 0;

        location = /health {
            access_log off;
            return 200 'ok';
        }

        location /static/ {
            alias /home/zulip/prod-static/;
            gzip_static on;
            add_header Access-Control-Allow-Origin *;
            add_header Timing-Allow-Origin *;
        }

{{- if $avatarProxyEnabled }}
        location {{ get $avatarProxy "pathPrefix" | default "/s3-avatar/" }} {
            proxy_pass {{ get $avatarProxy "upstreamUrl" }};
            proxy_set_header Host $proxy_host;
            proxy_hide_header Set-Cookie;
            add_header Cache-Control "public, max-age=31536000, immutable";
        }
{{- end }}

{{- if and (get $objectStorage "enabled") $s3InternalHost }}
        location ~ ^/internal/s3/{{ $s3InternalHost | regexQuoteMeta }}/(?<s3_path>.*) {
            internal;
            proxy_set_header Host {{ $s3EndpointHost | quote }};
            proxy_set_header Authorization "";
            proxy_set_header x-amz-security-token "";
            proxy_set_header Content-Length "";
            proxy_set_header Content-Type "";
            proxy_set_header Content-MD5 "";
            proxy_set_header x-amz-content-sha256 "";
            proxy_set_header Expect "";
            proxy_hide_header Cache-Control;
            proxy_hide_header Expires;
            proxy_hide_header Set-Cookie;
            rewrite ^/internal/s3/{{ $s3InternalHost | regexQuoteMeta }}/(.*)$ /$1 break;
            proxy_pass {{ printf "%s://%s" $s3EndpointScheme $s3EndpointHost }};
        }
{{- end }}

        location = /json/events {
            proxy_set_header Connection "";
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $zulip_forwarded_proto;
            proxy_pass $tornado_server;
            proxy_next_upstream off;
            proxy_redirect off;
            proxy_read_timeout 1200s;
            proxy_buffering off;
        }

        location = /api/v1/events {
            proxy_set_header Connection "";
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $zulip_forwarded_proto;
            proxy_pass $tornado_server;
            proxy_next_upstream off;
            proxy_redirect off;
            proxy_read_timeout 1200s;
            proxy_buffering off;
        }

{{- range $port := .Values.tornado.ports }}
        location ~ ^/internal/tornado/{{ $port }}(/.*)$ {
            internal;
            proxy_set_header Connection "";
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $zulip_forwarded_proto;
            proxy_pass http://tornado{{ $port }}$1$is_args$args;
            proxy_next_upstream off;
            proxy_redirect off;
            proxy_read_timeout 1200s;
            proxy_buffering off;
        }
{{- end }}

{{- if .Values.web.tusd.enabled }}
        location /api/v1/tus {
            proxy_request_buffering off;
            proxy_buffering off;
            proxy_pass http://tusd;
        }
{{- end }}

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $zulip_forwarded_proto;
            proxy_pass http://django;
        }
    }
}
{{- end }}
