{{- if and .Values.enabled .Values.homeserverProxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cinny.homeserverProxyName" . }}
  labels:
    {{- include "cinny.homeserverProxyLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cinny.homeserverProxySelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/homeserver-proxy-configmap.yaml") . | sha256sum }}
        {{- with .Values.homeserverProxy.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cinny.homeserverProxySelectorLabels" . | nindent 8 }}
        {{- with .Values.homeserverProxy.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.homeserverProxy.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: homeserver-proxy
          image: "{{ .Values.homeserverProxy.image.repository }}:{{ .Values.homeserverProxy.image.tag }}"
          imagePullPolicy: {{ .Values.homeserverProxy.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /_matrix/client/versions
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /_matrix/client/versions
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
          resources:
            {{- toYaml .Values.homeserverProxy.resources | nindent 12 }}
          {{- with .Values.homeserverProxy.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "cinny.homeserverProxyName" . }}
      {{- with .Values.homeserverProxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.homeserverProxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.homeserverProxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
