{{- if and .Values.enabled .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cinny.fullname" . }}
  labels:
    {{- include "cinny.labels" . | nindent 4 }}
  {{- if or .Values.certManager.enabled .Values.ingress.annotations }}
  annotations:
    {{- include "cinny.certManagerAnnotations" . | nindent 4 }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    {{- range .Values.ingress.hosts }}
    - {{- if .host }}
      hosts:
        - {{ .host | quote }}
      {{- end }}
      secretName: {{ default (printf "%s-tls" (include "cinny.fullname" $)) $.Values.ingress.tls.secretName | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - {{- if .host }}
      host: {{ .host | quote }}
      {{- end }}
      http:
        paths:
          {{- $paths := .paths | default (list (dict "path" "/" "pathType" "Prefix")) }}
          {{- range $paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "cinny.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
