{{- if and .Values.cinny.enabled (not .Values.cinny.config.create) }}
{{- $homeservers := .Values.cinny.config.homeserverList | default (list .Values.serverName) }}
{{- $config := dict "defaultHomeserver" (int .Values.cinny.config.defaultHomeserver) "homeserverList" $homeservers "allowCustomHomeservers" .Values.cinny.config.allowCustomHomeservers "featuredCommunities" .Values.cinny.config.featuredCommunities "hashRouter" .Values.cinny.config.hashRouter }}
{{- with .Values.cinny.config.extraConfig }}
{{- $config = mergeOverwrite $config . }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tuwunel.cinnyConfigMapName" . }}
  labels:
    {{- include "tuwunel.cinnyLabels" . | nindent 4 }}
data:
  config.json: |
    {{- $config | toPrettyJson | nindent 4 }}
{{- end }}
