# Relay Secrets for sensitive configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "relay.fullname" . }}-secrets
  labels:
    {{- include "relay.labels" . | nindent 4 }}
type: Opaque
data:
  # Relay-specific secrets
  NB_AUTH_SECRET: {{ $.Values.global.netbird.relay.secret | b64enc | quote }}