{{- if .Values.enabled }}
# Signal Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "signal.fullname" . }}
  labels:
    {{- include "signal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "signal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "signal.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: signal
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ $.Values.global.timezone | quote }}
          ports:
            - name: signal
              containerPort: 10000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: signal-var
              mountPath: /var/lib/netbird
      volumes:
        - name: signal-var
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "signal.fullname" . }}-var
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}