{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "livekit.secretName" . }}
  labels:
    {{- include "livekit.labels" . | nindent 4 }}
type: Opaque
stringData:
  api_key: {{ .Values.apiKey | quote }}
  api_secret: {{ .Values.apiSecret | quote }}
{{- end }}
