{{- if and .Values.enabled .Values.persistence.enabled }}
# Management PVCs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "management.fullname" . }}-etc
  labels:
    {{- include "management.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.etc.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "management.fullname" . }}-var
  labels:
    {{- include "management.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.var.size }}
{{- end }}