# Management Secrets for sensitive configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "management.fullname" . }}-secrets
  labels:
    {{- include "management.labels" . | nindent 4 }}
type: Opaque
data:
  # PostgreSQL secrets
  {{- if $.Values.global.postgresql.external.enabled }}
  POSTGRES_PASSWORD: {{ $.Values.global.postgresql.external.password | b64enc | quote }}
  {{- else if $.Values.global.postgresql.cnpg.enabled }}
  POSTGRES_PASSWORD: {{ $.Values.global.postgresql.cnpg.password | default "postgres" | b64enc | quote }}
  {{- end }}
  
  # PostgreSQL DSN strings
  {{- if $.Values.global.postgresql.external.enabled }}
  # External PostgreSQL
  NETBIRD_STORE_ENGINE_POSTGRES_DSN: {{ printf "host=%s user=%s password=%s dbname=%s port=%d"
    $.Values.global.postgresql.external.host
    $.Values.global.postgresql.external.user
    $.Values.global.postgresql.external.password
    $.Values.global.postgresql.external.database
    $.Values.global.postgresql.external.port | b64enc | quote }}
  NB_ACTIVITY_EVENT_POSTGRES_DSN: {{ printf "host=%s user=%s password=%s dbname=%s port=%d"
    $.Values.global.postgresql.external.host
    $.Values.global.postgresql.external.user
    $.Values.global.postgresql.external.password
    $.Values.global.postgresql.external.database
    $.Values.global.postgresql.external.port | b64enc | quote }}
  {{- else if $.Values.global.postgresql.cnpg.enabled }}
  # CNPG PostgreSQL
  NETBIRD_STORE_ENGINE_POSTGRES_DSN: {{ printf "host=%s-postgresql-rw user=postgres password=%s dbname=postgres port=5432"
    $.Release.Name
    ($.Values.global.postgresql.cnpg.password | default "postgres") | b64enc | quote }}
  NB_ACTIVITY_EVENT_POSTGRES_DSN: {{ printf "host=%s-postgresql-rw user=postgres password=%s dbname=postgres port=5432"
    $.Release.Name
    ($.Values.global.postgresql.cnpg.password | default "postgres") | b64enc | quote }}
  {{- end }}