{{- if .Values.enabled }}
# Management Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "management.fullname" . }}
  labels:
    {{- include "management.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "management.selectorLabels" . | nindent 4 }}
{{- end }}